### ISSUE TITLE
Effective Ruby

### ISSUE THREAD

**Issue by dai199** [okadai-techlab/how-to-study-language#10]
- [x] 第1章
- [x] 第2章
- [x] 第3章
- [x] 第4章
- [x] 第5章
- [x] 第6章
- [x] 第7章
- [x] 第8章

よし！！

**Comment by dai199** [comment]
:+1:

**Comment by dai199** [comment]
ひええええ

**Comment by dai199** [comment]
長年（数ヶ月）置きに置いたこの本を読み終えました！ふほー難しかったからまた何回か読むかぐぐろ！ｗお疲れ様でした！

**Comment by totzyuta** [comment]
:tada: :tada: :tada:
