### ISSUE TITLE
[PROGRESS] メタプログラミングRuby

### ISSUE THREAD

**Issue by totzyuta** [okadai-techlab/how-to-study-language#13]
- [x] Chapter 1 オブジェクトモデル
- [x] Chapter 2 メソッド
- [x] Chapter 3 ブロック
- [x] Chapter 4 クラス定義
- [x] Chapter 5 コードを記述するコード
- [x] Chapter 6 エピローグ 
- [x] Chapter 7 ActiveRecordの設計
- [x] Chapter 8 ActiveRecordの中身
- [x] Chapter 9 安全なメタプログラミング
- [x] Chapter 付録A: よく使うイディオム
- [x] Chapter 付録B: ドメイン特化言語
- [x] Chapter 付録C: 魔術書
- [x] Chapter 付録E: から騒ぎ

**Comment by totzyuta** [comment]
実践Ruby on Rails #3 途中ですが一旦こっちやりますw

**Comment by totzyuta** [comment]
3章と4章おわった〜〜〜 :relaxed: 

3章: https://github.com/totzyuta/magick-of-ruby/tree/master/chapter3_block
4章: https://github.com/totzyuta/magick-of-ruby/tree/master/chapter4_class-definition

**Comment by totzyuta** [comment]
Chapter5, 6おわった！

Chapter 5: https://github.com/totzyuta/magick-of-ruby/tree/master/chapter5_kernel-eval

ついにActiveRecord...！ :octocat:

**Comment by dai199** [comment]
:+1:

**Comment by totzyuta** [comment]
第二版も勢いで買ったので、1おわったらこっちもやってみる。

前半は軽くばーっと復習で、一版はgemがふるすぎたので (Rails 2か3だったw) そこをしっかり読み直そうかなー :smirk:

**Comment by totzyuta** [comment]
ついにおわった！！！！めちゃくちゃ面白かったーーーー！！！

Rubyist必読な一冊だなと思いました :heart_eyes: 
Rubyが大好きになること間違いなしです。
