### ISSUE TITLE
Fix Driver!

### ISSUE THREAD

**Issue by hyungjun010** [okadai-techlab/how-to-study-language#7]
今、使っているFedora 22でnouveauというオープンソースのLinuxの基本ディスプレイドライバと僕のノートパソコンのGeforce GTX 860Mのドライバの間にCrashが行い、Gnomeにブート不可になってしまった。
何回再設置しても同じようになるから、今回原因を見つけた後安定的な環境を作ることを目指している！

**Comment by totzyuta** [comment]
昨日なってたやつか...笑

なおった！？

**Comment by hyungjun010** [comment]
まだですね！Fedora 22は多分今年の5月末に公開されてまだ不安定だと思います。（笑）
言語設定後昨日のようになって設定を間違ったのかなと思いましたがそうでもなかったそうで～
それに、僕のノートパソコン様もなかなかLinuxさんとは親しくなりたくなさそうですね！？
CentOSやUbuntuでもインストールの画面からグラフィックに問題が発生するしどんなUSBツールで設置USBを作っても同じですね！

ああ、もしかしたらUSBに問題があるのかな？でもWindowsの設置では全然問題なかったです。

とにかく、僕のノートパソコンではHackintoshも不可、Linuxも不安定ｗｗｗｗｗ
VMは使いたくない！！！！
早めにマックブック買わなきゃ（笑）
